[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
semdiff-core = { path = "crates/semdiff-core" }
semdiff-output = { path = "crates/semdiff-output" }
semdiff-tree-fs = { path = "crates/semdiff-tree-fs" }
semdiff-differ-text = { path = "crates/semdiff-differ-text" }
semdiff-differ-binary = { path = "crates/semdiff-differ-binary" }

askama = "0.12.1"
clap = { features = ["derive"], version = "4.5.32" }
infer = "0.19.0"
memmap2 = "0.9.9"
mime = "0.3.17"
mime_guess = "2.0.5"
serde = { features = ["derive"], version = "1.0.218" }
serde_json = "1.0.139"
thiserror = "2.0.18"
