[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "semdiff-core"
version = { workspace = true }

[dependencies]
rayon = { workspace = true }
thiserror = { workspace = true }
