[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "semdiff-core"
version = { workspace = true }

[dependencies]
rayon = { workspace = true }
infer = { workspace = true }
memmap2 = { workspace = true }
mime = { workspace = true }
mime_guess = { workspace = true }
thiserror = { workspace = true }
