[package]
edition = { workspace = true }
name = "semdiff-differ-json"
version = { workspace = true }

[dependencies]
askama = { workspace = true }
mime = { workspace = true }
semdiff-core = { workspace = true }
semdiff-output = { workspace = true }
semdiff-tree-fs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
similar = { workspace = true }
thiserror = { workspace = true }
