[package]
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
name = "semdiff-differ-json"
version = { workspace = true }

[dependencies]
askama = { workspace = true }
mime = { workspace = true }
semdiff-core = { workspace = true }
semdiff-output = { workspace = true }
serde = { workspace = true }
serde_json = { features = ["preserve_order"], workspace = true }
similar = { workspace = true }
thiserror = { workspace = true }
