[package]
edition = { workspace = true }
name = "semdiff-output"
version = { workspace = true }

[dependencies]
dashmap = { workspace = true }
semdiff-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
